% ======================================================================
%> @brief Linearly spaced dates from start to stop dates provided.
%> @param startDateNum The start date number that the ordered data cell should
%> begin at.  (should be generated using datenum())
%> @param stopDateNum The date number (generated using datenum()) that the ordered data cell
%> ends at.
%> @param dateNumDelta The difference between two successive date number samples.
%> @param sampledDateVec Vector of date number values taken between startDateNum
%> and stopDateNum (inclusive) and are in the order and size as the
%> individual cell components of tmpDataCell
%> @retval synthDateNum Vector of date numbers corresponding to the date vector
%> matrix return argument.
%> @retval synthDateVec Matrix of date vectors ([Y, Mon,Day, Hr, Mn, Sec]) generated by
%> startDateNum:dateNumDelta:stopDateNum which correponds to the
%> row order of orderedDataCell cell values/vectors

%> @author Hyatt Moore IV
%======================================================================
function [synthDateNum, synthDateVec] = datespace(startDateNum, stopDateNum, dateNumDelta)
    synthDateVec = datevec(startDateNum:dateNumDelta:stopDateNum);
    synthDateVec(:,6) = round(synthDateVec(:,6)*1000)/1000;
    synthDateNum = datenum(synthDateVec);
end
